import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core";

/**
 * TOTP countdown ring. Pure presentation — the container computes `remaining`
 * (seconds left in the current step) and updates it each tick; the actual TOTP
 * code is generated by core's TotpService via the bridge, never here.
 */
@Component({
  selector: "kls-totp-ring",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "tw-inline-flex" },
  template: `
    <svg
      [attr.width]="size()"
      [attr.height]="size()"
      [attr.viewBox]="'0 0 ' + size() + ' ' + size()"
      role="img"
      [attr.aria-label]="remaining() + ' seconds until code refresh'"
    >
      <circle
        [attr.cx]="center()"
        [attr.cy]="center()"
        [attr.r]="radius()"
        fill="none"
        stroke="rgb(var(--color-gray-500) / 0.35)"
        [attr.stroke-width]="stroke()"
      />
      <circle
        [attr.cx]="center()"
        [attr.cy]="center()"
        [attr.r]="radius()"
        fill="none"
        [attr.stroke]="color()"
        [attr.stroke-width]="stroke()"
        stroke-linecap="round"
        [attr.stroke-dasharray]="circumference()"
        [attr.stroke-dashoffset]="dashOffset()"
        [attr.transform]="'rotate(-90 ' + center() + ' ' + center() + ')'"
        style="transition: stroke-dashoffset 1s linear, stroke 0.3s linear"
      />
      <text
        [attr.x]="center()"
        [attr.y]="center()"
        text-anchor="middle"
        dominant-baseline="central"
        [attr.font-size]="size() * 0.4"
        fill="currentColor"
        class="tw-font-mono tw-text-fg-body"
      >
        {{ remaining() }}
      </text>
    </svg>
  `,
})
export class KlsTotpRingComponent {
  /** Step length in seconds (default 30). */
  readonly period = input<number>(30);
  /** Seconds remaining in the current step. */
  readonly remaining = input.required<number>();
  readonly size = input<number>(36);

  protected readonly stroke = computed(() => Math.max(2, this.size() * 0.08));
  protected readonly center = computed(() => this.size() / 2);
  protected readonly radius = computed(() => this.center() - this.stroke());
  protected readonly circumference = computed(() => 2 * Math.PI * this.radius());

  protected readonly dashOffset = computed(() => {
    const frac = Math.min(1, Math.max(0, this.remaining() / this.period()));
    return this.circumference() * (1 - frac);
  });

  /** Brand colour, switching to danger in the final 5 seconds. */
  protected readonly color = computed(() =>
    this.remaining() <= 5 ? "rgb(var(--color-danger-600))" : "rgb(var(--fk-totp-progress))",
  );
}
